version: "3.7"

services:
  jenkins:
    build: 
      context: .
      dockerfile: jenkinsDockerfile
      
    # image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock    
    networks:
      - springapimysql-net

volumes:
  jenkins_home:

networks:
  springapimysql-net:
